config/routes.rb
Rails.application.routes.draw do
  root 'schools#index'

  resources :schools
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students, dependent: :destroy

  validates :name, :address, :principal, :capacity, presence: true
  validates :name, uniqueness: true
  validates :capacity, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 52000 }
  
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school
  
  validates :name, :student_number, :gpa, presence: true
  validates :name, uniqueness: true
  validates :student_number, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10000}

 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :load_school, only: %i(show edit update destroy)

  def index
    @school = School.all
  end

  def show
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    if @school.save
      redirect_to(school_path(@school), notice: "School added")
    else
      flash.now.alert = "Error saving school" 
      render(:new)
    end
  end

  def edit
  end

  def update
    load_school
    if @school.update(school_params)
      redirect_to(school_path(@school), notice: "School updated")
    else
      flash.now.alert = "Error saving school"
      render(:edit)
    end
  end

  def destroy
    load_school
    @school.destroy
    redirect_to(schools_path, notice: "School deleted")
  end

  private

  def load_school
    @school = School.find(params[:id])
  end

  def school_params
    params.require(:school).permit(:name, :address, :principal, :capacity, :private_school)
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :set_school
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /schools/1/students
  def index
    @students = @school.students.all
  end

  # GET /schools/1/students/1
  def show
  end

  # GET /schools/1/students/new
  def new
    @student = @school.students.new
  end

  # GET /schools/1/students/1/edit
  def edit
  end

  # POST /schools/1/students
  def create
    @student = @school.student.new(student_params)

    if @student.save
      redirect_to @student, notice: 'Student is created'
    else
      render :new
    end
  end

  # PUT/PATCH /schools/1/students/1
  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Student is updated'
    else
      render :edit
    end
  end

  # DELETE /schools/1/students/1
  def destroy
    @student.destroy
    redirect_to school_students_path(@school), notice: 'School is deleted'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:school_id])
    end

    def set_student
      @student = @school.students.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.require(:student).permit(:name, :student_number, :gpa)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_school
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /schools/1/students
  def index
    @students = @school.students.all
  end

  # GET /schools/1/students/1
  def show
  end

  # GET /schools/1/students/new
  def new
    @student = Student.new
  end

  # GET /schools/1/students/1/edit
  def edit
  end

  # POST /schools/1/students
  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student, notice: 'Student is created'
    else
      render :new
    end
  end

  # PUT/PATCH /schools/1/students/1
  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Student is updated'
    else
      render :edit
    end
  end

  # DELETE /schools/1/students/1
  def destroy
    @student.destroy
    redirect_to school_path(@school), notice: 'School is deleted'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @load_school
    end

    def set_student
      Student.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.require(:student).permit(:name, :student_number, :gpa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolSpecs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schools/_form.html.erb
<p>
<div>
  <%= f.label(:name) %><br>
  <%= f.text_field(:name) %>
</div>
<div>
  <%= f.label(:address) %><br>
  <%= f.text_area(:address) %>
</div>
<div>
  <%= f.label(:principal) %><br>
  <%= f.text_field(:principal) %>
</div>
<div>
  <%= f.label(:capacity) %><br>
  <%= f.number_field(:capacity) %>
</div>
<div>
  <%= f.label(:private_school) %>
  <%= f.check_box(:private_school) %>
</div>
</p>

app/views/schools/edit.html.erb
<h1>Schools#edit</h1>

<%= form_for(@school) do |f| %>
  <%= render("form", f: f) %>
  <%= f.submit("Save") %>
<% end %>

app/views/schools/index.html.erb
<h1>Schools</h1>
<%= link_to("Add School", new_school_path) %>

<ul>
<% @school.each do |school| %>
  <li>
    <%= school.name %>
    
    - 
      <%= link_to("show", school_path(school)) %>
      <%= link_to("edit", edit_school_path(school)) %>
      <%= link_to("delete", school_path(school), method: :delete, data: {confirm: "Delete?"}) %>
  </li>
<% end %>
</ul>

app/views/schools/new.html.erb
<h1>School#new</h1>
<%= form_for(@school) do |f| %>
  <%= render("form", f: f) %>
  <%= f.submit("Save") %>
<% end %>

app/views/schools/show.html.erb
<h1>Schools#show</h1>
<%= link_to("Add student", new_student_path(@school)) %>

  <% @school.students.each do |student| %>
  <ul>
      <li><%= student.name %>

      -
        <%= link_to("show", student_path) %>
        <%= link_to("edit", edit_student_path(@school, student)) %>
        <%= link_to("delete", student_path(@school, student), method: :delete, data: {confirm: "Delete?"}) %>
      </li>
    </ul>
  <% end %>
</ul>

app/views/students/_form.html.erb
<p>
<div>
  <%= f.label(:name) %><br>
  <%= f.text_field(:name) %>
</div>
<div>
  <%= f.label(:student_number) %><br>
  <%= f.text_area(:student_number) %>
</div>
<div>
  <%= f.label(:GPA) %><br>
  <%= f.text_area(:gpa) %>
</div>
</p>

<%# t.bigint "school_id"
    t.string "name", null: false
    t.integer "student_number", default: 0, null: false
    t.float "gpa", default: 0.0, null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false %>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

app/views/students/new.html.erb
<h1>Students#new</h1>
<%= form_for(@student) do |f| %>
  <%= render("form", f: f) %>
  <%= f.submit("Save") %>
<% end %>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>